name: Generate Contribution Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight UTC

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@master
        with:
          github_user_name: MohsinMuzamil
          outputs: github-contribution-grid-snake.svg

      - name: Commit generated file to 'output' branch
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Generated contribution snake"
